-- AlterTable
ALTER TABLE "User" ALTER COLUMN "email" DROP NOT NULL;
ALTER TABLE "User" ALTER COLUMN "onboarded" DROP NOT NULL;
ALTER TABLE "User" ALTER COLUMN "city" DROP NOT NULL;
ALTER TABLE "User" ALTER COLUMN "location" DROP NOT NULL;
ALTER TABLE "User" ALTER COLUMN "userType" DROP NOT NULL;
